cluster:
  targets:
    - name: n1
      host: 172.28.128.3
      sshKey: /opt/apps/neat/id_rsa
    - name: n2
      host: 172.28.128.4
      sshKey: /opt/apps/neat/id_rsa
    - name: n3
      host: 172.28.128.5
      sshKey: /opt/apps/neat/id_rsa

tester:
  random:
    period: 30
    hyena:
      - 127.0.0.1:12345
      - 127.0.0.1:22345
    kafka: 127.0.0.1:9292
    topic: hyena
    dim: 128